query SearchOrders($filter: OrderFilterInput, $first: Int!, $after: String) {
  orders(
    filter: $filter
    first: $first
    after: $after
    sortBy: { field: CREATED_AT, direction: DESC }
  ) {
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        number
        created
        status
        user {
          id
          email
          firstName
          lastName
        }
      }
    }
  }
}
